DataBinding.iml, mobile/build.gradle, mobile/src/main/AndroidManifest.xml, mobile/src/main/java/com/chaos/databinding/activities/MainActivity.java, mobile/src/main/java/com/chaos/databinding/adapters/RepoAdapter.java, mobile/src/main/java/com/chaos/databinding/services/GitHub.java, mobile/src/main/res/layout/activity_main.xml, mobile/src/main/res/menu/menu_main.xml, mobile/src/main/res/values/strings.xml
Implement a search view from the action bar instead of using a pre set username to search for repositories.
Include an 'empty' view to show when there are no items available.
=> Searchview

mobile/src/main/java/com/chaos/databinding/activities/BaseActivity.java, mobile/src/main/java/com/chaos/databinding/activities/MainActivity.java, mobile/src/main/res/layout/activity_main.xml, mobile/src/main/res/values-w820dp/dimens.xml, mobile/src/main/res/values/colors.xml, mobile/src/main/res/values/styles.xml
Implement the application compatibility library action bar for material style display of action bar with dark theme using custom primary and accent colours.
=> Material Actionbar

google-cloud/cloud-run/src/main/terraform/backend.tf, google-cloud/gh-oidc/src/main/terraform/variables.tf
- Include updated repository name
- Move backend to accessible bucket
=> Move Google Cloud Terraform backend"

.github/renovate.json, .github/workflows/renovate.yml
- Sign git commit with GPG private key
- Use correct bot email address
=> Playground Manager Email

.github/renovate.json
Reverts ashdavies/playground.ashdavies.dev#155
=> Revert "Explicitly specify renovate repositories"

.github/renovate.json
- Specify package groups for activity and lifecycle
- Match package patterns
=> Renovate Package Rules

.github/renovate.json, gradle/libs.versions.toml
- Specify package groups for activity and lifecycle
- Match package patterns
- Include google maven url
- Specify available repositories
=> Package Rules

.github/workflows/google-cloud.yml, .github/workflows/pre-merge.yml
See https://github.com/gradle/gradle-build-action/issues/630
=> Include gradle-home-cache-cleanup flag

gradle/wrapper/gradle-wrapper.properties
Reverts ashdavies/playground.ashdavies.dev#241
=> Revert "chore(deps): update dependency gradle to v8.1.1 (main)"

build.gradle.kts, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
- Revert "chore(deps): update dependency gradle to v8.1.1 (main) (#241)"
- Use version catalog for google services version
=> Google Services Version

.github/workflows/google-cloud.yml, .github/workflows/integration-test.yml, README.md
=> Update existing references

google-cloud/src/main/resources/openapi-v2.yml
- chore(openapi-v2.yml): add empty security array to the /events endpoint to disable authentication for now
- Trigger Build
=> Trigger Build

dominion-app/src/commonMain/kotlin/io/ashdavies/dominion/home/ExpansionService.kt, dominion-app/src/commonMain/kotlin/io/ashdavies/dominion/home/HomeScreen.kt, dominion-app/src/commonMain/kotlin/io/ashdavies/dominion/kingdom/CardService.kt, dominion-app/src/commonMain/kotlin/io/ashdavies/dominion/kingdom/KingdomScreen.kt, gradle/libs.versions.toml
=> Implementation no longer reflects ViewModel purposes

gradle/libs.versions.toml
Reverts ashdavies/playground.ashdavies.dev#430
=> Revert "fix(deps): update dependency com.google.guava:listenablefuture to v9999 (main)"

cloud-run/build.gradle.kts, google-cloud/build.gradle.kts, google-cloud/src/main/terraform/main.tf, google-cloud/src/main/terraform/modules/google/cloud-run-endpoint/variables.tf, google-cloud/src/main/terraform/variables.tf, gradle.properties, http-client/build.gradle.kts, openapi-v2.yml
- Move openapi spec to project root with parameter declaration
=> Project OpenAPI specification

build-plugins/src/main/kotlin/io.ashdavies.spotless.gradle.kts, nsd-manager/build.gradle.kts, nsd-manager/src/androidMain/AndroidManifest.xml, nsd-manager/src/androidMain/kotlin/io/ashdavies/nsd/NsdManager.android.kt, nsd-manager/src/commonMain/kotlin/io/ashdavies/nsd/NsdAgent.kt, nsd-manager/src/commonMain/kotlin/io/ashdavies/nsd/NsdManager.kt, nsd-manager/src/jvmMain/kotlin/io/ashdavies/nsd/NsdManager.jvm.kt, settings.gradle.kts
- Create NsdManager proxy service for android with stub JVM
- Adjust code style
=> Android/Jvm NsdManager

after-party/build.gradle.kts, after-party/src/commonMain/kotlin/io/ashdavies/events/EventsFactory.kt, after-party/src/commonMain/kotlin/io/ashdavies/gallery/GalleryFactory.kt, after-party/src/commonMain/kotlin/io/ashdavies/gallery/GalleryPresenter.kt, after-party/src/commonMain/kotlin/io/ashdavies/party/AfterPartyFactory.kt, after-party/src/commonMain/kotlin/io/ashdavies/party/AfterPartyScreen.kt, app-launcher/common/build.gradle.kts, app-launcher/common/src/commonMain/kotlin/io/ashdavies/playground/LauncherFactory.kt, app-launcher/common/src/commonMain/kotlin/io/ashdavies/playground/LauncherPresenter.kt, app-launcher/common/src/jvmTest/kotlin/io/ashdavies/playground/LauncherPresenterTest.kt, circuit-support/build.gradle.kts, circuit-support/src/commonMain/kotlin/io/ashdavies/circuit/Presenter.kt, circuit-support/src/commonMain/kotlin/io/ashdavies/circuit/Ui.kt, dominion-app/build.gradle.kts, dominion-app/src/commonMain/kotlin/io/ashdavies/dominion/DominionFactory.kt, dominion-app/src/commonMain/kotlin/io/ashdavies/dominion/DominionPresenter.kt, map-routes/build.gradle.kts, map-routes/src/commonMain/kotlin/io/ashdavies/routes/RouteFactory.kt, map-routes/src/commonMain/kotlin/io/ashdavies/routes/RoutePresenter.kt, map-routes/src/commonMain/kotlin/io/ashdavies/routes/RouteScreen.kt, settings.gradle.kts
- Create circuit support module for assisted factory creation
- Use when statements for consistency
=> Circuit Factory Support

gradle/libs.versions.toml
Reverts ashdavies/playground.ashdavies.dev#1225
=> Revert "fix(deps): update dependency com.google.firebase:firebase-admin to v9.4.0"

.github/actions/pull-comment/action.yml
Reverts ashdavies/playground.ashdavies.dev#1234
=> Revert "chore(deps): update thollander/actions-comment-pull-request action to v3"

app-check/app-check-sdk/src/commonMain/kotlin/io/ashdavies/check/FirebaseApp.kt, conferences-app/build.gradle.kts, conferences-app/src/androidMain/kotlin/io/ashdavies/party/MainActivity.kt, conferences-app/src/commonMain/kotlin/io/ashdavies/party/config/RemoteConfig.kt, conferences-app/src/commonMain/kotlin/io/ashdavies/party/events/paging/EventPager.kt, conferences-app/src/jvmMain/kotlin/io/ashdavies/party/Main.kt, conferences-app/src/jvmMain/kotlin/io/ashdavies/party/firebase/EmptyLocalConfigValue.kt, conferences-app/src/jvmMain/kotlin/io/ashdavies/party/firebase/LocalConfigValue.kt, remote-config/build.gradle.kts, remote-config/src/commonMain/kotlin/io/ashdavies/config/LazyRemoteConfig.kt, remote-config/src/commonMain/kotlin/io/ashdavies/config/LocalConfigValue.kt, remote-config/src/commonMain/kotlin/io/ashdavies/config/LocalRemoteConfig.kt, remote-config/src/commonMain/kotlin/io/ashdavies/config/RemoteConfig.kt
=> Conferences Desktop

.github/workflows/pull-request.yml
- **Upload missing rules artifact**
- **Remove required workflow condition**
=> Once more with feeling
